---
title: "Publications"
---

## Research (Primary author or Co-author)

1.  **Trend of Lassa fever cases and factors associated with mortality in Liberia, 2016 - 2021: a secondary data analysis** DOI**:** [10.11604/pamj.2024.47.22.42156](https://doi.org/10.11604/pamj.2024.47.22.42156) CONTRIBUTORS: Emmanuel Dwalu; Ralph Weah Jetoh; Bode Ireti Shobayo; Irene Pewu; Fahn Taweh; **Himiede Wede Wilson-Sesay**; Godwin Etim Akpan; Fulton Shannon; Babalola Obafemi Joseph; Chukwuma David Umeokonkwo et al.

2.  **COVID-19 vaccine hesitancy among adults in Liberia, April–May 2021** DOI: [10.1371/journal.pone.0297089](https://doi.org/10.1371/journal.pone.0297089) CONTRIBUTORS: Lily Sanvee- Blebo; Peter A. Adewuyi; Faith K. Whesseh; Obafemi Joseph Babalola; **Himiede W. Wilson-Sesay**; Godwin E. Akpan; Chukwuma Umeokonkwo; Peter Clement; Maame Amo-Addae

3.  **The influence of first wave of COVID-19 outbreak on routine healthcare services, Liberia, August 2020: a mixed study approach** DOI: [10.1186/s12913-022-08074-3](https://doi.org/10.1186/s12913-022-08074-3) CONTRIBUTORS: Obafemi J. Babalola; **Himiede W. Sesay**; Lily S. Blebo; Faith K. Whesseh; Chukwuma D. Umeokonkwo; Peter A. Adewuyi; Maame Amo-Addae

4.  **COVID-19 reinfection in Liberia: Implication for improving disease surveillance.** DOI: [10.1371/journal.pone.0265768](https://doi.org/10.1371/journal.pone.0265768) CONTRIBUTORS: Godwin Akpan; Bawo L; Amo-Addae M; Jallah Kennedy; Wesseh CS; Whesseh F; Adebayo Peter Adewuyi; Sanvee-Blebo L; Babalola J; **Sesay HWW** et al

5.  **Post-ebola syndrome among ebola virus disease survivors in Montserrado County, Liberia 2016** DOI: [10.1155/2018/1909410](https://doi.org/10.1155/2018/1909410) CONTRIBUTORS: **Wilson, H.W.**; Amo-Addae, M.; Kenu, E.; Ilesanmi, O.S.; Ameme, D.K.; Sackey, S.O.

6.  **Outbreak of Neisseria meningitidis serogroup C outside the meningitis belt—Liberia, 2017: an epidemiological and laboratory investigation** DOI: [10.1016/s1473-3099(18)30476-6](https://doi.org/10.1016/s1473-3099(18)30476-6) CONTRIBUTORS: Catherine H Bozio; Jeni Vuong; E Kainne Dokubo; Mosoka P Fallah; Lucy A McNamara; Caelin C Potts; John Doedeh; Miatta Gbanya; Adam C Retchless; Jaymin C Patel et al.

7.  **Rapid field response to a cluster of illnesses and deaths Sinoe county, Liberia, April-May, 2017** DOI: [10.15585/mmwr.mm6642a4](https://doi.org/10.15585/mmwr.mm6642a4) CONTRIBUTORS: Doedeh, J.; Frimpong, J.A.; Yealue, K.D.M.; **Wilson, H.W**.; Konway, Y.; Wiah, S.Q.; Doedeh, V.; Bao, U.; Seneh, G.; Gorwor, L. et al.

8.  **Contraceptive Methods Accessed in Volta Region, Ghana, 2009–2014** DOI: [10.1155/2017/7257042](https://doi.org/10.1155/2017/7257042) CONTRIBUTORS: **Himiede W. Wilson**, Donne K. Ameme, Olayinka Stephen Ilesanmi

9.  **A Three Year Review of Tuberculosis Surveillance Data in Montserrado County, Liberia, 2016-2018** CONTRIBUTORS: Alberta Berlynda Corvah, **Himiede Wilson Sesay,** Delia Akosua Bandoh, Patrick Konwloh, Benedict Calys-Tagoe, Ernest Kenu https://www.afenet-journal.net//content/article/6/3/full/

10. **Episodes of confirmed malaria and associated factors in patients attending selected health facilities, Liberia, 2015-2016: A cross-sectional study** DOI:[10.37432/jieph.supp.2021.4.3.01.10](http://dx.doi.org/10.37432/jieph.supp.2021.4.3.01.10) CONTRIBUTORS: Victor Senkolo Koko, Diboulo Eric, Levi Hinneh, Joseph Alade, Oliver James Pratt, Nelson Dunber, Maame Amo-Addae, Fulton Shannon, **Himiede Wilson,** Obafemi Babalola, Delia Bandoh, Adewuyi Peter

11. **Knowledge, attitudes and practices (KAP) regarding Lassa fever disease among adults in endemic and non-endemic Counties of Liberia, 2018: A Cross-sectional study** DOI:[10.37432/jieph.supp.2021.4.2.01.9](http://dx.doi.org/10.37432/jieph.supp.2021.4.2.01.9) CONTRIBUTORS: Darius Dolopei, Maame Amo-Addae, Adewuyi Peter, **Himiede Wilson,** Fulton Shannon, Jimmy Lawubah, Ophelia Woods, Oscar Gbearr, Vivian Kemah Deodeh, Austine Sanley, Miatta Wright Kullie, George Tamatia, Jacob Muyan, Lincoln Gbabow, Torwon George Bunnah, Allakemanie Sackie, Harrison Duo, Darius Leyhen, Edwin Paye, Phebe Thomas

12. **Building Epidemiological Capacity for Health Security in Liberia**                   DOI: 10.11604/JIEPH.supp.2021.4.1.1143 CONTRIBUTORS: Muhammad Shakir Balogun, Maame Amo-Addae, **Wede Himiede Wilson**

13. **Is Schistosomiasis present in Grand Kru County, Liberia, 2018?** (http://www.afenet-journal.net/content/series/4/1/3/full/) DOI:[10.37432/jieph.supp.2021.4.1.01.3](https://doi.org/10.37432/jieph.supp.2021.4.1.01.3) CONTRIBUTORS: Emmanuel Ghartey, Fulton Quincy Shannon II, Peter Adewuyi, Maame Amo-Addae, **Himiede Wede Wilson,** Olayinka Stephen Ilesanmi, Thomas Knue Nagbe, Obafemi Joseph Babalola Journal of Intervention Epidemiology and Public Health

14. **Lassa fever outbreak in Newaken Community, Grand Kru County, Liberia, September-October 2017** DOI:[10.37432/jieph.supp.2021.4.1.01.4](http://dx.doi.org/10.37432/jieph.supp.2021.4.1.01.4) CONTRIBUTORS: Jimmy Gboluma Lawubah, Maame Amo-Addae, Peter Adewuyi, Fulton Quincy Shannon**,** **Himiede Wede Wilson**, Lilian Bulage, Olayinka Ilesanmi, Elijah Edu-Quansah, Obafemi Joseph Babalola, Thomas Nagbe Journal of Intervention Epidemiology and Public Health

15. **Monkeypox Outbreak, Harper District, Maryland County, Liberia, December 2017** DOI:[10.11604/JIEPH.SUPP.2021.4.1.1015](https://doi.org/10.11604/JIEPH.SUPP.2021.4.1.1015) CONTRIBUTORS: Dedesco Doebia Gweh, Peter Adewuyi, Maame Amo-Addae, Lilian Bulage, **Himiede Wede Wilson**, Fulton Shannon II, Olayinka Stephen Ilesanmi, Thomas Knue Nagbe, Obafemi Joseph Babalola

16. **Review of Maternal Deaths in Lofa County, Liberia, 2015- 2017** DOI:[10.37432/jieph.supp.2021.4.1.01.6](http://dx.doi.org/10.37432/jieph.supp.2021.4.1.01.6) CONTRIBUTORS: Tamba Saah Alpha, Darius Dolopei, Esther Argbah, Ngormbu Jusu Ballah, Lavala Bigboy Kortimai, Joseph Asamoah Frimgpong, Maame Amo-Addae, Peter Adewuyi, Olayinka Ilesanmi, Fulton Shannon, **Himiede Wilson**, Richard Kerkulah Vanyanteh Mulbah, Julius Rude Monday

17. **Maternal choices of delivery sites among recently delivered women in Liberia, 2017** DOI:[10.11604/JIEPH.SUPP.2021.4.1.1080](https://doi.org/10.11604/JIEPH.SUPP.2021.4.1.1080) CONTRIBUTORS: Gabriel Boumen Kassay, Ben Gbouh, Dedesco Gweh, Emmanuel Dweh, Emmanuel Ghartey, Felecia Dweh, Lawrence Larway, Leroy Maximore, Moses Fomba, Sylvester Toe, Tamba Alpha, Faith Whesseh, Roseline George, Trokon Yeabah, Olayinka Stephen Ilesanmi, Peter Adewuyi, Fulton Shannon II, **Wede Himiede Wilson**, Obafemi Babalola, Thomas Nagbe, Maame Amo-Addae

18. **Risk Factors associated with a Gastroenteritis Outbreak, Firestone District, Margibi County, Liberia, February 2018** DOI:[10.37432/jieph.supp.2021.4.2.01.8](http://dx.doi.org/10.37432/jieph.supp.2021.4.2.01.8) CONTRIBUTORS: Leroy Stephen Maximore, Maame Amo-Addae, Peter Adewuyi, Fulton Shannon, **Himiede Wilson,** Obafemi Babalola, Olayinka Ilesanmi, Thomas Nagbe Journal of Intervention Epidemiology and Public Health

19. **Knowledge Attitude and Preventive Practices of COVID-19 among Health Workers, Liberia, 2020** DOI:[10.37432/jieph.supp.2023.6.1.06.5](https://doi.org/10.37432/jieph.supp.2023.6.1.06.5) CONTRIBUTORS: **Himiede Sesay**, Godwin Etim Akpan, Peter Adebayo Adewuyi, Obafemi Joseph Babalola, Lily Sanvee Blebo, Faith Kamara Whesseh, Maame Amo-Addae
